# patients_xlsx = "https://drive.google.com/uc?export=download&id=1ElxGwoKobfUkBaryPu1o5bnkWx2iUdHc"
# inspections_xlsx = "https://drive.google.com/uc?export=download&id=1dhjaRyKGFai_rOHjmdjrQq2rtpG5UKq8"
data_json_filename = "data.json"
#patients_and_inspections_xlsx = "https://drive.google.com/uc?export=download&id=1sUhxGBWMRNrL-HQlfVgtuGXgn6U7I873"
#contacts1_xlsx = "https://drive.google.com/uc?export=download&id=1T67ffjyUqj2DDXQmRzLZcwg-fZfYmOAZ"
#contacts2_xlsx = "https://drive.google.com/uc?export=download&id=1iMA3Zh1KUiiKdWGJ7LtB8DVDqwEzzyap"
patients_and_inspections_xlsx = "https://drive.google.com/uc?export=download&id=1mDzPdQ1zRI9wjqlofisOqvY5GBlOZDEd"
contacts1_xlsx = "https://drive.google.com/uc?export=download&id=1FE0eMM-sk6CPk9OOMidYhvU-nXGAVcga"
contacts2_xlsx = "https://drive.google.com/uc?export=download&id=1dmwTIkwXcfSu0rvxuV2H4mlDJDJOJa3d"
