# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy JSON Files

on:
  schedule:
    - cron:  '*/2 * * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tool/requirements.txt
    - name: Run script
      run: |
        python ./tool/main.py
    - name: Pull request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Bot: data.jsonの更新"
        title: "Bot: data.jsonの更新"
        base: development
        branch: data-bot/development
